#! /usr/bin/env bash

# Returns the path to the Local by Flywheel shell files appending a path.
function local_ssh_entry(){
		echo "${HOME}"/Library/Application\ Support/Local\ by\ Flywheel/ssh-entry/
}

# Starts an SSH session in a specific machine, identified by its name.
function local-ssh(){
		if [ $# -lt 1 ]; then 
				echo "Usage: local-ssh <site>"
				echo ''
				echo "Examples"
				echo "--------"
				echo ''
				echo "Open a bash prompt in the project machine:"
				echo "local-ssh <project>"

				return
		fi

		dir="$(local_ssh_entry)"
		file=$(ag "${1}" "${dir}" --files-with-matches)

		if [[ -z "${file}" ]];then 
				echo "No Local site found for ${1}."
				return
		fi

		sh "${file}"
}

# Prints the IP address of the Local By Flywheel Docker machine.
function local-machine-ip(){
		cat "${HOME}""/Library/Application Support/Local by Flywheel/machine-ip.json"
}

# Opens an SSH session into the Local Docker machine.
function local-machine-ssh(){
		machine_address="$(local-machine-ip)"
		ssh -i ~/.docker/machine/machines/local-by-flywheel/id_rsa docker@"${machine_address}"
}

# Output the IP Address of the Local by Flywheel host machine.
function local-host-ip(){
		VBoxManage guestproperty get local-by-flywheel /VirtualBox/GuestInfo/Net/2/V4/IP \
		| grep Value \
		| cut -f2 -d: \
		| tr -d ' '
}

# Serve the current directory on localhost:8080.
function lserve(){
		LOCALHOST_WP=1 wp server
}
